### ISSUE TITLE
Error message: Your DirectAdmin settings are wrong.

### ISSUE THREAD

**Issue by stgoos** [t-me/DireactAdmin-Certificate-Manager#5]
@t-me thanks for this initiative! Hopefully our hoster will have their fully integrated solution available soon as well :)

Just installed it with a copy of the files available at Nov 25 @ 1830 and I'm able to log on but I get the following error message:

```
Notice: Undefined index: list in /home/***/domains/mydomainname.ext/public_html/certmanager/lib/functions.php on line 150

Warning: Invalid argument supplied for foreach() in /home/***/domains/mydomainname.ext/public_html/certmanager/lib/functions.php on line 150

Notice: Undefined index: list in /home/***/domains/mydomainname.ext/public_html/certmanager/lib/functions.php on line 122
ERROR
Your DirectAdmin settings are wrong. Please check and correct them.
```

The DA host credential is like: mydomainname.ext, **so without :2223**. Is this the right approach?
I've also tried it with ***.webhostingserver.nl as the direct address.

Username and password are the same I normally logon to DA with so that should be fine.

For completeness: I've currently 2 domains configured in DA and have installed DACM in the main/first domain.

Any thoughts?

**Comment by t-me** [comment]
Hello @stgood,

If you are hosted at the Antagonist you need the xxx.webhostingserver.nl as host. Then it will work. 

If you not hosted there, can you tell me your hostingprovider?

**Comment by stgoos** [comment]
Yep - I'm with Antagonist too.

Thanks for the hint. I normally connect to DA via port 2223 instead of 2222, so I thought the issue came from there as I noticed only port 2222 in the DA_CONNECT() function (lib/functions.php:106).

Played with that but then discovered that you actually need to include the https:// in front of the ***.webhostingserver,nl address. So it works now.

Is it perhaps an idea to make the protocol a mandatory part of the provided DirectAdmin host URL?

Also could it potentially be that hosts block access via port 2222?
If so, then it might actually be an idea to request the port number as well on the settings page.
